### PR TITLE
Improving Directory Structure

### PR DESCRIPTION
**Pull request by Tanvi141**
#### Brief description of what is fixed or changed
Created templates directory and moved cuda files from util/ and cuda/ to cuda/util and cuda/core respectively. All include statements also updated.

### CODE REVIEW

**Comment by czgdp1807** [comment]
Can you please show the reports of CUDA tests? You have a GPU on your system right?

**Comment by Tanvi141** [comment]
@czgdp1807 yes I do, please let me know how I can generate reports of the tests.

**Comment by czgdp1807** [comment]
```cpp
~/codezonediitj/build-adaboost$ cmake -DBUILD_TESTS=ON -DBUILD_CUDA=ON ../adaboost
-- The CXX compiler identification is GNU 7.5.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for a CUDA compiler
-- Looking for a CUDA compiler - /usr/local/cuda-10.2/bin/nvcc
-- The CUDA compiler identification is NVIDIA 10.2.89
-- Check for working CUDA compiler: /usr/local/cuda-10.2/bin/nvcc
-- Check for working CUDA compiler: /usr/local/cuda-10.2/bin/nvcc -- works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/czgdp1807ssd/codezonediitj/build-adaboost
czgdp1807ssd@czgdp1807ssd-Inspiron-7570:~/codezonediitj/build-adaboost$ make -j5Scanning dependencies of target adaboost_utils
Scanning dependencies of target adaboost_cuda
Scanning dependencies of target adaboost_cuda_wrappers
Scanning dependencies of target adaboost_core
[  5%] Building CXX object adaboost/CMakeFiles/adaboost_utils.dir/utils/utils_impl.cpp.o
[ 11%] Building CUDA object adaboost/CMakeFiles/adaboost_cuda_wrappers.dir/cuda/utils/cuda_wrappers_impl.cu.o
[ 17%] Building CUDA object adaboost/CMakeFiles/adaboost_cuda.dir/cuda/utils/cuda_wrappers_impl.cu.o
[ 23%] Building CUDA object adaboost/CMakeFiles/adaboost_cuda.dir/cuda/core/cuda_data_structures_impl.cu.o
[ 29%] Building CXX object adaboost/CMakeFiles/adaboost_core.dir/core/data_structures_impl.cpp.o
[ 35%] Linking CXX shared library ../libs/libadaboost_utils.so
[ 35%] Built target adaboost_utils
[ 41%] Building CXX object adaboost/CMakeFiles/adaboost_core.dir/core/operations_impl.cpp.o
/home/czgdp1807ssd/codezonediitj/adaboost/adaboost/cuda/core/cuda_data_structures_impl.hpp(147): warning: 'long double' is treated as 'double' in device code

/home/czgdp1807ssd/codezonediitj/adaboost/adaboost/cuda/core/cuda_data_structures_impl.hpp(360): warning: 'long double' is treated as 'double' in device code

[ 47%] Building CXX object adaboost/CMakeFiles/adaboost_core.dir/utils/utils_impl.cpp.o
[ 52%] Linking CUDA device code CMakeFiles/adaboost_cuda_wrappers.dir/cmake_device_link.o
[ 58%] Linking CUDA shared library ../libs/libadaboost_cuda_wrappers.so
[ 58%] Built target adaboost_cuda_wrappers
[ 64%] Linking CXX shared library ../libs/libadaboost_core.so
[ 64%] Built target adaboost_core
Scanning dependencies of target test_core
[ 70%] Building CXX object adaboost/CMakeFiles/test_core.dir/tests/test_core.cpp.o
[ 76%] Linking CXX executable ../bin/test_core
[ 76%] Built target test_core
[ 82%] Linking CUDA device code CMakeFiles/adaboost_cuda.dir/cmake_device_link.o
[ 88%] Linking CUDA shared library ../libs/libadaboost_cuda.so
[ 88%] Built target adaboost_cuda
Scanning dependencies of target test_cuda
[ 94%] Building CXX object adaboost/CMakeFiles/test_cuda.dir/tests/test_cuda.cpp.o
[100%] Linking CXX executable ../bin/test_cuda
[100%] Built target test_cuda
czgdp1807ssd@czgdp1807ssd-Inspiron-7570:~/codezonediitj/build-adaboost$ cd bin
czgdp1807ssd@czgdp1807ssd-Inspiron-7570:~/codezonediitj/build-adaboost/bin$ ls
test_core  test_cuda
czgdp1807ssd@czgdp1807ssd-Inspiron-7570:~/codezonediitj/build-adaboost/bin$ ./test_cuda
[==========] Running 2 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 2 tests from Cuda
[ RUN      ] Cuda.VectorGPU
[       OK ] Cuda.VectorGPU (62 ms)
[ RUN      ] Cuda.MatrixGPU
[       OK ] Cuda.MatrixGPU (3 ms)
[----------] 2 tests from Cuda (65 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 1 test suite ran. (65 ms total)
[  PASSED  ] 2 tests.
czgdp1807ssd@czgdp1807ssd-Inspiron-7570:~/codezonediitj/build-adaboost/bin$ ./test_core
[==========] Running 4 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 4 tests from Core
[ RUN      ] Core.Vector
[       OK ] Core.Vector (0 ms)
[ RUN      ] Core.Matrices
[       OK ] Core.Matrices (0 ms)
[ RUN      ] Core.Sum
[       OK ] Core.Sum (0 ms)
[ RUN      ] Core.Argmax
[       OK ] Core.Argmax (0 ms)
[----------] 4 tests from Core (0 ms total)

[----------] Global test environment tear-down
[==========] 4 tests from 1 test suite ran. (0 ms total)
[  PASSED  ] 4 tests.
```
The tests are passing.

**Comment by czgdp1807** [comment]
All Okay. Ready for merge. Thanks.

**Pull request merged**
